machine:
  services:
    - docker

dependencies:
  pre:
    - docker info
test:
  override:
    - make build

deployment:
  hub_branch:
    branch: master
    commands:
      - docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASSWORD quay.io
      - make push
